import { useState, useEffect } from "react";
import { ItemForm, ItemData } from "@/components/ItemForm";
import { ItemBoard } from "@/components/ItemBoard";
import { ClipboardList } from "lucide-react";

const Index = () => {
  const [items, setItems] = useState<ItemData[]>([]);

  // OnPageLoad: Fetch all items from backend
  useEffect(() => {
    // This is where you would fetch from your backend (Firebase/Supabase)
    // Example: fetchItemsFromBackend().then(data => setItems(data));
    
    // For now, loading from localStorage for demo purposes
    const savedItems = localStorage.getItem("lostFoundItems");
    if (savedItems) {
      setItems(JSON.parse(savedItems));
    }
  }, []);

  // OnSubmit: Send form data to backend
  const handleSubmit = (data: Omit<ItemData, "id">) => {
    const newItem: ItemData = {
      id: Date.now().toString(), // In production, this would be generated by your backend
      ...data,
    };

    // This is where you would send to your backend (Firebase/Supabase)
    // Example: sendItemToBackend(newItem);
    
    // For demo, saving to localStorage
    const updatedItems = [newItem, ...items];
    setItems(updatedItems);
    localStorage.setItem("lostFoundItems", JSON.stringify(updatedItems));

    // The JSON format that would be sent to backend:
    console.log("Data sent to backend:", JSON.stringify(newItem, null, 2));
  };

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="border-b bg-card shadow-sm">
        <div className="container mx-auto px-4 py-6">
          <div className="flex items-center gap-3">
            <ClipboardList className="h-8 w-8 text-primary" />
            <div>
              <h1 className="text-3xl font-bold text-foreground">Lost & Found Board</h1>
              <p className="text-sm text-muted-foreground">
                Help reunite lost items with their owners
              </p>
            </div>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="container mx-auto px-4 py-12 space-y-16">
        {/* Form Section */}
        <section>
          <ItemForm onSubmit={handleSubmit} />
        </section>

        {/* Board Section */}
        <section>
          <div className="text-center mb-8">
            <h2 className="text-3xl font-bold mb-2">Community Board</h2>
            <p className="text-muted-foreground">
              Browse through posted items and help make connections
            </p>
          </div>
          <ItemBoard items={items} />
        </section>
      </main>

      {/* Footer */}
      <footer className="border-t mt-16 py-8 bg-muted/30">
        <div className="container mx-auto px-4 text-center text-sm text-muted-foreground">
          Lost & Found Board - Built with React & TypeScript
        </div>
      </footer>
    </div>
  );
};

export default Index;
